ShengsenEmployeeDistributionMap/ShengsenEmployeeDistributionMap/Models/POCO/Employees.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShengsenEmployeeDistributionMap.Models
{
    /// <summary>
    /// 員工資訊 POCO
    /// </summary>
    public partial class Employees
    {
        [Key]
        [StringLength(50)]
        public string Id { get; set; }

        [Required]
        [StringLength(50)]
        [Description("員工姓名")]
        public string EmployeeName { get; set; }

        [Required]
        [StringLength(10)]
        [Description("縣市代碼")]
        public string CityCode { get; set; }

        [Required]
        [StringLength(10)]
        [Description("鄉、鎮市區代碼")]
        public string DistrictCode { get; set; }

        [StringLength(50)]
        [Description("駐點公司代碼")]
        public string CompanyId { get; set; }

        [Required]
        [StringLength(10)]
        [Description("技能")]
        public string Department { get; set; }

        [Required]
        [Description("類別(來源)")]
        public int Category { get; set; }

        [StringLength(20)]
        [Description("四型人格")]
        public string Personality { get; set; }

        [Required]
        [StringLength(100)]
        [Description("學歷/學位")]
        public string Education { get; set; }
        
        [MaxLength]
        [Description("經歷")]
        public string WorkExperience { get; set; }

        [Required]
        [Description("工程師總年資")]
        [Column(TypeName = "Date")]
        public DateTime StartWorkDate { get; set; }

        [MaxLength]
        [Description("住所地址")]
        public string Residence { get; set; }

        [Required]
        [Description("性別")]
        public int Gender { get; set; }

        [MaxLength]
        [Description("技能描述")]
        public string SkillDescription { get; set; }

        [MaxLength]
        [Description("備註")]
        public string Remark { get; set; }

        [Description("建立日期")]
        [Column(TypeName = "Date")]
        public DateTime? CreateDate { get; set; }

        [Description("聖森到職日期")]
        [Column(TypeName = "Date")]
        public DateTime? OnBoardDate { get; set; }

        [Description("駐點日期")]
        [Column(TypeName = "Date")]
        public DateTime? LocationedDate { get; set; }

        [Description("出生年月日")]
        [Column(TypeName = "Date")]
        public DateTime? Birthday { get; set; }
    }
}

ShengsenEmployeeDistributionMap/ShengsenEmployeeDistributionMap/Controllers/EmployeesController.cs
using ShengsenEmployeeDistributionMap.Models;
using ShengsenEmployeeDistributionMap.Models.BLO;
using ShengsenEmployeeDistributionMap.Models.DMO;
using ShengsenEmployeeDistributionMap.Models.ViewModel.In;
using System;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShengsenEmployeeDistributionMap.Controllers
{
    /// <summary>
    /// 員工
    /// </summary>
    [Authorize]
    public class EmployeesController : Controller
    {
        private EmployeesBLO _EmployeesBLO = new EmployeesBLO();

        public EmployeesController()
        {
            _EmployeesBLO = new EmployeesBLO();
        }

        //Amy: 頁面搜尋條件設定
        // GET: Employees
        public ActionResult Index()
        {
            return View();
        }

        #region 員工新增/編輯

        /// <summary>
        /// 新增/編輯
        /// </summary>
        /// <param name="id">員工編號</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CreateOrEdit(string id)
        {
            try
            {
                ViewBag.IsExist = !string.IsNullOrEmpty(id);    //是否已存在DB，判斷是新增還是編輯

                //新增
                if (string.IsNullOrEmpty(id))
                {
                    InEmployeesValidationViewModel viewModel = new InEmployeesValidationViewModel();
                    viewModel.Id = id;
                    //開始工作日期設為今日
                    viewModel.StartWorkDateString = DateTime.Now.ToShortDateString();
                    return View(viewModel);
                }
                //編輯
                else
                {
                    Employees employees = _EmployeesBLO.GetAll().FirstOrDefault(x => x.Id.Equals(id));

                    //防呆檢查
                    if (employees == null)
                        return HttpNotFound();
                    else
                        return View(employees.ToInEmployeesValidationViewModel());
                }
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // POST: Employees/CreateOrEdit
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit([Bind(Exclude = "CitySelectListItems,DistrictSelectListItems,StationedCompanySelectListItems")] InEmployeesValidationViewModel item)
        {
            try
            {
                #region 設定預設值

                item.CreateDate = DateTime.Now;
                item.BirthdayString = item.Birthday?.ToShortDateString();
                item.StartWorkDateString = item.StartWorkDate.ToShortDateString();
                item.OnBoardDateString = item.OnBoardDate?.ToShortDateString();
                item.LocationedDateString = item.LocationedDate?.ToShortDateString();
                ViewBag.IsExist = !string.IsNullOrEmpty(item.Id);    //是否已存在DB，判斷是新增還是編輯

                #endregion 設定預設值

                //欄位驗證
                if (ModelState.IsValid)
                {
                    int result = 0; //是否成功

                    //新增
                    if (string.IsNullOrEmpty(item.Id))
                    {
                        //設定GUID
                        item.Id = Guid.NewGuid().ToString();

                        result = _EmployeesBLO.Create(item.ToEmployees());
                    }
                    //編輯
                    else
                    {
                        result = _EmployeesBLO.Update(item.ToEmployees());
                    }

                    if (result > 0)
                        return RedirectToAction("Index");
                    else
                        return View(item);
                }

                //驗證失敗的訊息
                var errors = ModelState.Values.Where(x => x.Errors.Count() > 0);

                return View(item);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        #endregion 員工新增/編輯

        #region 匯入功能

        /// <summary>
        /// 匯入員工資料
        /// </summary>
        /// <param name="importFile"></param>
        /// <returns></returns>
        public ActionResult ImportEmployeesData(HttpPostedFileBase importFile)
        {
            try
            {
                //檢查是否上傳檔案
                if (importFile != null)
                {
                    #region 檢查檔案格式

                    //取得副檔名，並檢查是否是EXCEL格式
                    string FileExtension = System.IO.Path.GetExtension(importFile.FileName);
                    if (FileExtension != ".xlsx")
                        throw new Exception("檔案格式不符");

                    //檢查檔案大小是否 > 5 MB
                    if (importFile.ContentLength > 5 * 1024 * 1024)
                        throw new Exception("檔案大小超過5MB");

                    #endregion 檢查檔案格式

                    #region 暫存檔案到excelTemp資料夾

                    string appPath = Path.Combine(Request.PhysicalApplicationPath, "Content\\ExcelTemps");
                    if (!Directory.Exists(appPath))
                    {
                        Directory.CreateDirectory(appPath);
                    }

                    var physicalPath = Path.Combine(appPath, importFile.FileName);
                    importFile.SaveAs(physicalPath);

                    #endregion 暫存檔案到excelTemp資料夾

                    //開始匯入
                    bool isSuccess = _EmployeesBLO.ImportEmployeesData(physicalPath);

                    #region 刪除檔案

                    if (System.IO.File.Exists(physicalPath))
                    {
                        System.IO.File.Delete(physicalPath);
                    }

                    #endregion 刪除檔案

                    if (isSuccess)
                        return Json("匯入成功", JsonRequestBehavior.AllowGet);
                    else
                        return Json("匯入失敗", JsonRequestBehavior.AllowGet);
                }
                else
                    throw new Exception("請匯入檔案");
            }
            catch (Exception ex)
            {
                if (importFile != null)
                {
                    string appPath = Path.Combine(Request.PhysicalApplicationPath, "Content\\ExcelTemps");
                    if (!Directory.Exists(appPath))
                    {
                        Directory.CreateDirectory(appPath);
                    }

                    var physicalPath = Path.Combine(appPath, importFile.FileName);
                    System.IO.File.Delete(physicalPath);    //刪除檔案
                }
                return Json(ex.Message + (Path.Combine(System.IO.Directory.GetCurrentDirectory(), "Content\\ExcelTemps", importFile.FileName)), JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 匯入範本下載
        /// </summary>
        /// <returns></returns>
        public ActionResult ImportTemplateData()
        {
            try
            {
                string filePath = Server.MapPath("~/Content/ExcelTemplate/ImportTemplate.xlsx");
                // 暫存
                string GUID = Guid.NewGuid().ToString();
                TempData[GUID] = _EmployeesBLO.ExportImportTemplate(filePath).ToArray();

                return Json(new { FileGuid = GUID, FileName = "匯入檔案範本.xlsx" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion 匯入功能

        #region 匯出

        /// <summary>
        /// 匯出報表暫存
        /// </summary>
        /// <returns></returns>
        public ActionResult ExportTemplateData()
        {
            try
            {
                string filePath = Server.MapPath("~/Content/ExcelTemplate/ImportTemplate.xlsx");
                // 暫存
                string GUID = Guid.NewGuid().ToString();
                TempData[GUID] = _EmployeesBLO.ExportEmployeeData(filePath).ToArray();

                return Json(new { Status = HttpStatusCode.OK, FileGuid = GUID, FileName = $"員工資訊_{DateTime.Now.ToString("yyyyMMdd")}.xlsx" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Status = HttpStatusCode.BadRequest, ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 下載
        /// </summary>
        /// <param name="fileGuid">暫存Key</param>
        /// <param name="fileName">下載檔名</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Download(string fileGuid, string fileName)
        {
            try
            {
                if (TempData[fileGuid] != null)
                {
                    byte[] data = TempData[fileGuid] as byte[];
                    return File(data, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
                }
                else
                {
                    return new EmptyResult();
                }
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion 匯出

        #region 求職者新增

        /// <summary>
        /// 求職者新增
        /// </summary>
        /// <param name="id">員工Id</param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public ActionResult JobSeekerViewOrEdit(string id)
        {
            try
            {
                //防呆檢查：一定要有員工Id
                if (string.IsNullOrEmpty(id))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                //檢查DB是否存在該筆資料

ShengsenEmployeeDistributionMap/ShengsenEmployeeDistributionMap/Views/Employees/JobSeekerViewOrEdit.cshtml
@model ShengsenEmployeeDistributionMap.Models.ViewModel.In.InEmployeesValidationViewModel

@{
    if (ViewBag.IsExist)
    {
        ViewBag.Title = "檢視資料";
    }
    else
    {
        ViewBag.Title = "新增資料";
    }

    //技能下拉選單
    List<SelectListItem> DepartmentList = new List<SelectListItem>() {
        new SelectListItem() { Value = "", Text = "--請選擇--" },
        new SelectListItem() { Value = "JAVA", Text = "JAVA" },
        new SelectListItem() { Value = ".NET", Text = ".NET" }
    };
}

<div id="app">
    <div class="d-flex justify-content-center p-3">
        <div class="card w-100 h-100 border-dark bg-light shadow rounded">
            @using (Html.BeginForm("JobSeekerViewOrEdit", "Employees", FormMethod.Post, new { id = "createForm"}))
            {
                <div class="card-header bg-transparent border-dark text-center">
                    <h3>@ViewBag.Title</h3>
                </div>
                <div class="card-body text-left text-sm-left text-md-right text-lg-right">
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group row">
                        @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="col-12 col-sm-12 col-md-10 col-lg-10">
                            @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control", placeholder = "該欄必填" } })
                            @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger float-left" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-12 col-sm-12 col-md-2 col-lg-2 col-form-label">性別</label>
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            <div class="form-check form-check-inline float-left p-2">
                                <input class="form-check-input" type="radio" name="Gender" id="inlineRadio1" v-model="Gender" v-bind:value="0">
                                <label class="form-check-label" for="inlineRadio1">男</label>
                            </div>
                            <div class="form-check form-check-inline float-left p-2">
                                <input class="form-check-input" type="radio" name="Gender" id="inlineRadio2" v-model="Gender" v-bind:value="1">
                                <label class="form-check-label" for="inlineRadio2">女</label>
                            </div>
                        </div>
                        @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            <div class="input-group date" data-target-input="nearest">
                                <input id="Birthday" name="Birthday" type="text" class="form-control datetimepicker-input" data-target="#Birthday" v-model="Birthday" required />
                                <div class="input-group-append" data-target="#Birthday" data-toggle="datetimepicker">
                                    <div class="input-group-text">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Residence, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="col-12 col-sm-12 col-md-10 col-lg-10">
                            @Html.EditorFor(model => model.Residence, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Residence, "", new { @class = "text-danger float-left" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.CityCode, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            <select id="CityCode" name="CityCode" class="form-control" v-model="CityCode">
                                <option value="" selected>--請選擇--</option>
                                <option v-for="City in CitySelectListItems" v-bind:value="City.Value">{{ City.Text }}</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.CityCode, "", new { @class = "text-danger float-left" })
                        </div>
                        @Html.LabelFor(model => model.DistrictCode, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            <select id="DistrictCode" name="DistrictCode" class="form-control" v-model="DistrictCode">
                                <option value="" selected>--請選擇--</option>
                                <option v-for="District in DistrictSelectListItems" v-bind:value="District.Value">{{ District.Text }}</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.DistrictCode, "", new { @class = "text-danger float-left" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Education, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            @Html.EditorFor(model => model.Education, new { htmlAttributes = new { @class = "form-control", placeholder = "該欄必填" } })
                            @Html.ValidationMessageFor(model => model.Education, "", new { @class = "text-danger float-left" })
                        </div>
                        @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="col-12 col-sm-12 col-md-3 col-lg-3">
                            @Html.DropDownListFor(model => model.Department, DepartmentList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger float-left" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.WorkExperience, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="ml-3">
                            @Html.TextAreaFor(model => model.WorkExperience, 5, 500, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.WorkExperience, "", new { @class = "text-danger float-left" })
                        @Html.LabelFor(model => model.SkillDescription, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="ml-3">
                            @Html.TextAreaFor(model => model.SkillDescription, 5, 500, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.SkillDescription, "", new { @class = "text-danger float-left" })
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.StartWorkDate, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="col-12 col-sm-12 col-md-10 col-lg-10">
                            <div class="input-group date" data-target-input="nearest">
                                <input id="StartWorkDate" name="StartWorkDate" placeholder="該欄必填" type="text" class="form-control datetimepicker-input" data-target="#StartWorkDate" v-model="StartWorkDate" required />
                                <div class="input-group-append" data-target="#StartWorkDate" data-toggle="datetimepicker">
                                    <div class="input-group-text">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "col-12 col-sm-12 col-md-2 col-lg-2 col-form-label" })
                        <div class="ml-3">
                            @Html.TextAreaFor(model => model.Remark, 5, 500, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger float-left" })
                    </div>
                </div>

                if (ViewBag.IsExist == false)
                {
                    <div class="card-footer bg-transparent border-dark text-center">
                        <label>
                            <input v-on:click="funCreate();" value="新增" class="btn btn-primary" />
                        </label>
                    </div>
                }
            }
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(function () {
            //初始化日期
            $('#Birthday').datetimepicker({
                format: "YYYY/MM/DD",
                startDate: "today",
                todayHighlight: true,
                language: 'zh-TW'
            });
            $('#StartWorkDate').datetimepicker({
                format: "YYYY/MM/DD",
                startDate: "today",
                todayHighlight: true,
                language: 'zh-TW'
            });
        });
        const isExist = "@ViewBag.IsExist" == "True";
        const CityCode = "@Model.CityCode";
        const DistrictCode = "@Model.DistrictCode";
        const StartWorkDate = "@Model.StartWorkDateString"; //僅顯示yyyy/MM/dd
        const Birthday = "@Model.BirthdayString"; //僅顯示yyyy/MM/dd
        const Gender = "@Model.Gender";
        
        var app = new Vue({
            el: "#app",
            data: {
                CityCode: CityCode,
                DistrictCode: DistrictCode,
                CitySelectListItems: [],
                DistrictSelectListItems: [],
                StartWorkDate: StartWorkDate,
                Birthday: Birthday,
                Gender: Gender,
            },
            watch: {
                //縣市變更
                CityCode: function () {
                    //取得鄉鎮市區
                    $.ajax({
                        url: "/api/LivingAreaApi/GetDistrictSelectListItems?CityCode=" + this.CityCode,
                        type: "get",
                        contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                        success: function (data) {
                            app.DistrictSelectListItems = data.Result;
                        },
                    });
                },
            },
            methods: {
                funCreate: function() {
                    if (confirm("新增後就不可以修改，是否要新增？")) {
                        $("#createForm").submit();
                    }
                }
            },
            created: function () {
                //取得縣市
                $.ajax({
                    url: "/api/LivingAreaApi/GetCitySelectListItems",
                    type: "get",
                    contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                    success: function (data) {
                        app.CitySelectListItems = data.Result;
                    },
                });

                //取得鄉鎮市區
                $.ajax({
                    url: "/api/LivingAreaApi/GetDistrictSelectListItems?CityCode=" + this.CityCode,
                    type: "get",
                    contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                    success: function (data) {
                        app.DistrictSelectListItems = data.Result;
                    },
                });

                //檢視的話禁用所有欄位
                $('input,select,textarea').prop('disabled', isExist);
            }
        });
    </script>
}

ShengsenEmployeeDistributionMap/ShengsenEmployeeDistributionMap/Views/Employees/JobSeekerViewOrEditConfirmation.cshtml
@{
    ViewBag.Title = "新增資訊確認";
}

<div id="app">
    <div class="d-flex justify-content-center p-3">
        <div class="card h-100 border-dark bg-light col-12 col-sm-12 col-md-4 col-lg-4 shadow rounded">
            <form>
                <div class="card-header bg-transparent text-center">
                    <h3>@ViewBag.Title</h3>
                    <p>您的資料已輸入完畢，請自行關閉視窗</p>
                </div>
            </form>
        </div>
    </div>
</div>