ShengsenEmployeeDistributionMap/ShengsenEmployeeDistributionMap/Controllers/EmployeesDistributionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShengsenEmployeeDistributionMap.Controllers
{
    /// <summary>
    /// 員工分佈
    /// </summary>
    [Authorize]
    public class EmployeesDistributionController : Controller
    {
        // GET: EmployeesDistribution
        public ActionResult Index()
        {
            return View();
        }
    }
}

ShengsenEmployeeDistributionMap/ShengsenEmployeeDistributionMap/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>聖森 - 員工分佈</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*載入Vue.js CDN*@
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    @*Vue.js分頁組件*@
    <script src="https://unpkg.com/vuejs-paginate@latest"></script>
    @*Vue multi select*@
    <script src="https://unpkg.com/vue-multiselect@2.1.0"></script>
    <link rel="stylesheet" href="https://unpkg.com/vue-multiselect@2.1.0/dist/vue-multiselect.min.css">
    @*載入字體*@
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: Microsoft JhengHei, arial, verdana;
        }
    </style>
    @*載入icon*@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">
    @*Sweet Alert*@
    <script src="~/Scripts/src/utils/SweetAlert/SweetAlert2.js"></script>
    <link rel="stylesheet" href="~/Content/utils/SweetAlert/sweetalert2.min.css" />
    @*moment.js*@
    <script src="~/Scripts/src/utils/Moment/moment.js"></script>
</head>
<body class="bg-light">
    @if (Request.IsAuthenticated)
    {
        <div class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            @Html.ActionLink("員工分佈", "Index", "EmployeesDistribution", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">系統管理</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="~/Employees/Index">員工資訊</a>
                            <a class="dropdown-item" href="~/StationedCompany/Index">駐點公司資訊</a>
                            <a class="dropdown-item" href="~/LivingArea/Index">居住地區資訊</a>
                            <a class="dropdown-item" href="~/GroupManagement/Index">工程師群組</a>
                            <a class="dropdown-item" href="~/Account/Register">發送註冊邀請</a>
                        </div>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="~/SatisfactionSurvey/Index">客戶滿意度調查</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    }
    <div class="container-fluid">
        <noscript>
            <strong>
                We're sorry but google_api_practice doesn't work properly without JavaScript enabled. Please enable it to
                continue.
            </strong>
        </noscript>
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*載入bootstrap 4 datepicker*@
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
    @RenderSection("scripts", required: false)
</body>
</html>